# Generated by Django 3.0.4 on 2020-03-21 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_text',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Текст жалобы'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='flat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='property.Flat'),
        ),
    ]
