# Generated by Django 3.0.4 on 2020-03-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20200321_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_text',
            field=models.TextField(verbose_name='Текст жалобы'),
        ),
    ]
